# Generated by Django 4.2.13 on 2024-08-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_review_options_review_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliography',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
