# Generated by Django 4.2.13 on 2024-08-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_bibliography_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliography',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
